Test Report - 2025-04-04_16-21-37
==================================================

Total Tests Run: 15
Successful: 14
Failed: 1
Errors: 0
Run Time: 0:00:00.216838

Failed Tests:
--------------------
test_convert_to_pdf_file_too_large (test_pdf.TestPDFConversion.test_convert_to_pdf_file_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_pdf.py", line 76, in test_convert_to_pdf_file_too_large
    self.assertEqual(json_data['error'], 'Individual file size exceeds limit')
AssertionError: 'Total file size exceeds limit' != 'Individual file size exceeds limit'
- Total file size exceeds limit
? ^^^
+ Individual file size exceeds limit
? ^^^^^^^^



