Test Report - 2025-04-04_16-08-30
==================================================

Total Tests Run: 2
Successful: 0
Failed: 0
Errors: 2
Run Time: 0:00:00.000237

Errors:
--------------------
test_app (unittest.loader._FailedTest.test_app)
ImportError: Failed to import test module: test_app
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_app.py", line 5, in <module>
    from main import app
  File "/Users/ganeshbollem/Documents/image-resizer-app/main.py", line 1, in <module>
    from app import create_app
  File "/Users/ganeshbollem/Documents/image-resizer-app/app/__init__.py", line 6, in <module>
    from app.routes import init_routes
  File "/Users/ganeshbollem/Documents/image-resizer-app/app/routes.py", line 10, in <module>
    from app.config import UPLOAD_FOLDER, MAX_CONTENT_LENGTH, MAX_FILE_SIZE
ImportError: cannot import name 'MAX_CONTENT_LENGTH' from 'app.config' (/Users/ganeshbollem/Documents/image-resizer-app/app/config.py)



test_pdf (unittest.loader._FailedTest.test_pdf)
ImportError: Failed to import test module: test_pdf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_pdf.py", line 5, in <module>
    from main import app
  File "/Users/ganeshbollem/Documents/image-resizer-app/main.py", line 1, in <module>
    from app import create_app
  File "/Users/ganeshbollem/Documents/image-resizer-app/app/__init__.py", line 6, in <module>
    from app.routes import init_routes
  File "/Users/ganeshbollem/Documents/image-resizer-app/app/routes.py", line 10, in <module>
    from app.config import UPLOAD_FOLDER, MAX_CONTENT_LENGTH, MAX_FILE_SIZE
ImportError: cannot import name 'MAX_CONTENT_LENGTH' from 'app.config' (/Users/ganeshbollem/Documents/image-resizer-app/app/config.py)



