Test Report - 2025-04-04_16-14-15
==================================================

Total Tests Run: 15
Successful: 13
Failed: 2
Errors: 0
Run Time: 0:00:00.335048

Failed Tests:
--------------------
test_file_too_large (test_app.TestImageResizerApp.test_file_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_app.py", line 118, in test_file_too_large
    self.assertEqual(response.status_code, 413)
AssertionError: 400 != 413


test_convert_to_pdf_total_size_too_large (test_pdf.TestPDFConversion.test_convert_to_pdf_total_size_too_large)
Traceback (most recent call last):
  File "/Users/ganeshbollem/Documents/image-resizer-app/tests/test_pdf.py", line 121, in test_convert_to_pdf_total_size_too_large
    self.assertEqual(json_data['error'], 'Total file size exceeds limit')
AssertionError: 'File size exceeds limit' != 'Total file size exceeds limit'
- File size exceeds limit
? ^
+ Total file size exceeds limit
? ^^^^^^^



